version: '3'

services:  

  discovery-service:
    container_name: discovery-service
    image: armandorvila/discovery-service
    build:
      context: .
      dockerfile: ./discovery-service/src/main/docker/Dockerfile
    ports:
      - 8761:8761
    environment:
      SERVER_PORT: 8761

  
  transactions-service:
    image: armandorvila/transactions-service
    build:
      context: .
      dockerfile: ./transactions-service/src/main/docker/Dockerfile
    ports:
      - 8000
    environment:
      SERVER_PORT: 8000
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service

  
  acounts-service:
    image: armandorvila/acounts-service
    build:
      context: .
      dockerfile: ./accounts-service/src/main/docker/Dockerfile
    ports:
      - 8000
    environment:
      SERVER_PORT: 8000
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      
  
  edge-service:
    image: armandorvila/edge-service
    build:
      context: .
      dockerfile: ./edge-service/src/main/docker/Dockerfile
    ports:
      - 80:80
    environment:
      SERVER_PORT: 80
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service