version: '3'

services:  

  database:
    container_name: database
    image: mongo:3.6
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null

  discovery-service:
    container_name: discovery-service
    image: armandorvila/discovery-service
    build:
      context: .
      dockerfile: ./discovery-service/src/main/docker/Dockerfile
    ports:
      - 8761:8761
    environment:
      SPRING_PROFILES_ACTIVE: prod

  
  transactions-service:
    image: armandorvila/transactions-service
    build:
      context: .
      dockerfile: ./transactions-service/src/main/docker/Dockerfile
    ports:
      - 8000
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - discovery-service
      - database

  
  accounts-service:
    image: armandorvila/acounts-service
    build:
      context: .
      dockerfile: ./accounts-service/src/main/docker/Dockerfile
    ports:
      - 8000
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - discovery-service
      - database
      
  
  edge-service:
    image: armandorvila/edge-service
    build:
      context: .
      dockerfile: ./edge-service/src/main/docker/Dockerfile
    ports:
      - 80:80
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - discovery-service


  user-interface:
    image: armandorvila/accounts-user-interface
    build:
      context: .
      dockerfile: ./accounts-user-interface/Dockerfile
    ports:
      - 5000:80