server:
  port: 8080
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
        
spring:
  profiles:
    active:
 #   - prod Un comment this to work against an actual mongodb during development.